//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MauiEnterpriseApp.Resources.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MauiEnterpriseApp.Resources.Localization.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sunucudan geçerli bir yanıt alınamadı. Lütfen tekrar deneyin..
        /// </summary>
        internal static string Common_Error_EmptyResponse {
            get {
                return ResourceManager.GetString("Common_Error_EmptyResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beklenmeyen bir hata oluştu. Lütfen tekrar deneyin..
        /// </summary>
        internal static string Common_Error_Generic {
            get {
                return ResourceManager.GetString("Common_Error_Generic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ağ bağlantısı sağlanamadı. Lütfen internet bağlantınızı kontrol edin..
        /// </summary>
        internal static string Common_Error_Network {
            get {
                return ResourceManager.GetString("Common_Error_Network", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sunucuya erişilirken bir hata oluştu. Lütfen daha sonra tekrar deneyin..
        /// </summary>
        internal static string Common_Error_Server {
            get {
                return ResourceManager.GetString("Common_Error_Server", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Teknik bir sorun oluştu. Lütfen daha sonra tekrar deneyin..
        /// </summary>
        internal static string Common_Error_Technical {
            get {
                return ResourceManager.GetString("Common_Error_Technical", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giriş yapılıyor....
        /// </summary>
        internal static string Login_BusyText {
            get {
                return ResourceManager.GetString("Login_BusyText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giriş Yap.
        /// </summary>
        internal static string Login_Button {
            get {
                return ResourceManager.GetString("Login_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Demo kullanıcı:  test@demo.com / 123456.
        /// </summary>
        internal static string Login_DemoHint {
            get {
                return ResourceManager.GetString("Login_DemoHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-posta.
        /// </summary>
        internal static string Login_EmailLabel {
            get {
                return ResourceManager.GetString("Login_EmailLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ornek@eposta.com.
        /// </summary>
        internal static string Login_EmailPlaceholder {
            get {
                return ResourceManager.GetString("Login_EmailPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geçersiz e-posta veya şifre..
        /// </summary>
        internal static string Login_Error_Invalid {
            get {
                return ResourceManager.GetString("Login_Error_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hesabınız kilitlenmiş. Lütfen sistem yöneticinizle iletişime geçin..
        /// </summary>
        internal static string Login_Error_Locked {
            get {
                return ResourceManager.GetString("Login_Error_Locked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-posta ve şifre zorunludur..
        /// </summary>
        internal static string Login_Error_Required {
            get {
                return ResourceManager.GetString("Login_Error_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Şifre.
        /// </summary>
        internal static string Login_PasswordLabel {
            get {
                return ResourceManager.GetString("Login_PasswordLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ••••••••.
        /// </summary>
        internal static string Login_PasswordPlaceholder {
            get {
                return ResourceManager.GetString("Login_PasswordPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Devam etmek için giriş yapın.
        /// </summary>
        internal static string Login_Subtitle {
            get {
                return ResourceManager.GetString("Login_Subtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hoş geldiniz.
        /// </summary>
        internal static string Login_Title {
            get {
                return ResourceManager.GetString("Login_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giriş.
        /// </summary>
        internal static string Shell_Login_Title {
            get {
                return ResourceManager.GetString("Shell_Login_Title", resourceCulture);
            }
        }
    }
}
