//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MauiEnterpriseApp.Resources.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MauiEnterpriseApp.Resources.Localization.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to © 2025 Maui Enterprise.
        /// </summary>
        internal static string App_Flyout_Footer {
            get {
                return ResourceManager.GetString("App_Flyout_Footer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maui Enterprise.
        /// </summary>
        internal static string App_Name {
            get {
                return ResourceManager.GetString("App_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kurumsal .NET MAUI Uygulama Şablonu.
        /// </summary>
        internal static string App_Tagline {
            get {
                return ResourceManager.GetString("App_Tagline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sunucudan geçerli bir yanıt alınamadı. Lütfen tekrar deneyin..
        /// </summary>
        internal static string Common_Error_EmptyResponse {
            get {
                return ResourceManager.GetString("Common_Error_EmptyResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beklenmeyen bir hata oluştu. Lütfen tekrar deneyin..
        /// </summary>
        internal static string Common_Error_Generic {
            get {
                return ResourceManager.GetString("Common_Error_Generic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ağ bağlantısı sağlanamadı. Lütfen internet bağlantınızı kontrol edin..
        /// </summary>
        internal static string Common_Error_Network {
            get {
                return ResourceManager.GetString("Common_Error_Network", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sunucuya erişilirken bir hata oluştu. Lütfen daha sonra tekrar deneyin..
        /// </summary>
        internal static string Common_Error_Server {
            get {
                return ResourceManager.GetString("Common_Error_Server", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Teknik bir sorun oluştu. Lütfen daha sonra tekrar deneyin..
        /// </summary>
        internal static string Common_Error_Technical {
            get {
                return ResourceManager.GetString("Common_Error_Technical", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Form.
        /// </summary>
        internal static string Dashboard_Button_Form {
            get {
                return ResourceManager.GetString("Dashboard_Button_Form", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Liste / Detay.
        /// </summary>
        internal static string Dashboard_Button_List {
            get {
                return ResourceManager.GetString("Dashboard_Button_List", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profil.
        /// </summary>
        internal static string Dashboard_Button_Profile {
            get {
                return ResourceManager.GetString("Dashboard_Button_Profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ayarlar.
        /// </summary>
        internal static string Dashboard_Button_Settings {
            get {
                return ResourceManager.GetString("Dashboard_Button_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hızlı İşlemler.
        /// </summary>
        internal static string Dashboard_Section_QuickActions {
            get {
                return ResourceManager.GetString("Dashboard_Section_QuickActions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ana Sayfa.
        /// </summary>
        internal static string Dashboard_Title {
            get {
                return ResourceManager.GetString("Dashboard_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hoş geldiniz..
        /// </summary>
        internal static string Dashboard_Welcome_Generic {
            get {
                return ResourceManager.GetString("Dashboard_Welcome_Generic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hoş geldin, {0}.
        /// </summary>
        internal static string Dashboard_Welcome_WithName {
            get {
                return ResourceManager.GetString("Dashboard_Welcome_WithName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giriş yapılıyor....
        /// </summary>
        internal static string Login_BusyText {
            get {
                return ResourceManager.GetString("Login_BusyText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giriş Yap.
        /// </summary>
        internal static string Login_Button {
            get {
                return ResourceManager.GetString("Login_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Demo kullanıcı:  test@demo.com / 123456.
        /// </summary>
        internal static string Login_DemoHint {
            get {
                return ResourceManager.GetString("Login_DemoHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-posta.
        /// </summary>
        internal static string Login_EmailLabel {
            get {
                return ResourceManager.GetString("Login_EmailLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ornek@eposta.com.
        /// </summary>
        internal static string Login_EmailPlaceholder {
            get {
                return ResourceManager.GetString("Login_EmailPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geçersiz e-posta veya şifre..
        /// </summary>
        internal static string Login_Error_Invalid {
            get {
                return ResourceManager.GetString("Login_Error_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hesabınız kilitlenmiş. Lütfen sistem yöneticinizle iletişime geçin..
        /// </summary>
        internal static string Login_Error_Locked {
            get {
                return ResourceManager.GetString("Login_Error_Locked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-posta ve şifre zorunludur..
        /// </summary>
        internal static string Login_Error_Required {
            get {
                return ResourceManager.GetString("Login_Error_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Şifre.
        /// </summary>
        internal static string Login_PasswordLabel {
            get {
                return ResourceManager.GetString("Login_PasswordLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ••••••••.
        /// </summary>
        internal static string Login_PasswordPlaceholder {
            get {
                return ResourceManager.GetString("Login_PasswordPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Devam etmek için giriş yapın.
        /// </summary>
        internal static string Login_Subtitle {
            get {
                return ResourceManager.GetString("Login_Subtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hoş geldiniz.
        /// </summary>
        internal static string Login_Title {
            get {
                return ResourceManager.GetString("Login_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profili Düzenle.
        /// </summary>
        internal static string Profile_Button_Edit {
            get {
                return ResourceManager.GetString("Profile_Button_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profil bilgileri yüklenemedi..
        /// </summary>
        internal static string Profile_Empty_Message {
            get {
                return ResourceManager.GetString("Profile_Empty_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kullanıcı Profili.
        /// </summary>
        internal static string Profile_Header_Title {
            get {
                return ResourceManager.GetString("Profile_Header_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Departman.
        /// </summary>
        internal static string Profile_Label_Department {
            get {
                return ResourceManager.GetString("Profile_Label_Department", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-posta.
        /// </summary>
        internal static string Profile_Label_Email {
            get {
                return ResourceManager.GetString("Profile_Label_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ad Soyad.
        /// </summary>
        internal static string Profile_Label_FullName {
            get {
                return ResourceManager.GetString("Profile_Label_FullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sisteme Giriş.
        /// </summary>
        internal static string Profile_Label_JoinedDate {
            get {
                return ResourceManager.GetString("Profile_Label_JoinedDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telefon.
        /// </summary>
        internal static string Profile_Label_Phone {
            get {
                return ResourceManager.GetString("Profile_Label_Phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pozisyon.
        /// </summary>
        internal static string Profile_Label_Position {
            get {
                return ResourceManager.GetString("Profile_Label_Position", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profil yükleniyor....
        /// </summary>
        internal static string Profile_Loading_Message {
            get {
                return ResourceManager.GetString("Profile_Loading_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Temel Bilgiler.
        /// </summary>
        internal static string Profile_Section_BasicInfo {
            get {
                return ResourceManager.GetString("Profile_Section_BasicInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İletişim.
        /// </summary>
        internal static string Profile_Section_Contact {
            get {
                return ResourceManager.GetString("Profile_Section_Contact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profil.
        /// </summary>
        internal static string Profile_Title {
            get {
                return ResourceManager.GetString("Profile_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giriş.
        /// </summary>
        internal static string Shell_Login_Title {
            get {
                return ResourceManager.GetString("Shell_Login_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Koyu tema.
        /// </summary>
        internal static string Theme_Toggle_Dark {
            get {
                return ResourceManager.GetString("Theme_Toggle_Dark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Açık tema.
        /// </summary>
        internal static string Theme_Toggle_Light {
            get {
                return ResourceManager.GetString("Theme_Toggle_Light", resourceCulture);
            }
        }
    }
}
